/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package v1

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.core.subcommands
import com.github.ajalt.clikt.parameters.arguments.argument
import com.github.ajalt.clikt.parameters.arguments.multiple
import com.github.ajalt.clikt.parameters.types.int

class App: CliktCommand(){
    fun check() {
       TODO( "print results of 'countAllConflicts()' if greater than 0 print details")
    }
    private fun countAllConflicts() {
        TODO(" calls 'countConflicts()' on each queen position")
        //for (column in boardList) {
        //    countConflicts(boardList, column)
        //}
    }
    override fun run() {

    }

}

class CheckSubCommand: CliktCommand(
    name = "check"
) {
    val boardList: List<Int> by argument().int().multiple(required=true)
    override fun run() {
        println("checking...")
    }
}

fun main(args: Array<String>) = App().subcommands(CheckSubCommand()).main(args)
